apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: dify-api
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  type: LoadBalancer
