apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  namespace: {{ .Values.global.namespace }}
  labels:
    app: dify-env
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  # Shared environment variables
  {{- range $key, $val := .Values.sharedEnv }}
  {{ regexReplaceAll "([a-z0-9])([A-Z])" $key "${1}_${2}" | upper }}: {{ $val | quote }}
  {{- end }}