apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-plugin-daemon
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: dify-plugin-daemon
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: http
  type: LoadBalancer
