apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sandbox
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: dify-sandbox
  ports:
  - port: 8194
    targetPort: 8194
    protocol: TCP
    name: http
  type: LoadBalancer
