apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssrf-proxy
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: dify-ssrf-proxy
  ports:
  - port: 3128
    targetPort: 3128
    protocol: TCP
    name: http
  type: LoadBalancer
