apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plugin-daemon-storage
  namespace: {{ .Values.global.namespace }}
  annotations:
    helm.sh/resource-policy: keep  
spec:
  accessModes:
    - {{ .Values.volumes.storage.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.volumes.storage.resources.requests.storage | default "10Gi" }}
  storageClassName: {{ .Values.volumes.storage.storageClassName | default "standard" | quote }}