apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: dify-web
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer
